services:
  app:
    image: orel2287/pogoda
    container_name: pogodaapp-container
    command: python main.py

  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    depends_on:
      - app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 30 pogodaapp-container nginx-container

