name: Docker

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: orel2287/pogoda
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      - name: Get short commit hash
        id: shortsha
        run: echo "::set-output name=sha::$(git rev-parse --short $GITHUB_SHA)"
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  orel2287/pogoda:${{ steps.shortsha.outputs.sha }}
          labels: ${{ steps.metadata.outputs.labels }} 
