name: Docker

on:
  schedule:
    - cron: '44 21 * * *'
  push:
    branches: [latest]
    tags: [ 'latest' ]
  pull_request:
    branches: [latest]
  release:
    types: [created]

jobs:
  latest:
     
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker Hub auth
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: orel2287/pogoda
          tags: |
            type=schedule
            type=ref, event=branch
            type=ref, event=pr
            type=semver, pattern={{version}}

      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
