name: CI

on:
  push:
    branches:
      - latest
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ runner.os }}-latest
            ${{ runner.os }}-${{ github.ref_name }}
          publish: ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}
